import Head from 'next/head';
import Link from 'next/link';
import client from '../client';
import Image from 'next/image';
import NavBar from '../components/navigation/NavBar';
import TechSlider from '../components/technologies-sliders/TechSlider';

type Props = {};

const Home = ({}: Props) => {
  return (
    <div>
      <Head>
        <title>Tashinga</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <NavBar />

      <main id='main' className='min-h-[80vh] md:mt-[80px]'>
        <div className='w-full h-full bg-primary-700  pt-10 pb-20 text-white'>
          <div className='container-1 grid gap-14 md:gap-28'>
            <section className='grid gap-10 justify-center'>
              <article className='w-full grid md:grid-cols-5 gap-10 content-center justify-items-center'>
                <div className='flex flex-col gap-5 self-center justify-self-center md:col-span-3 max-w-lg md:max-w-none'>
                  <h1 className='text-4xl lg:text-5xl font-bold'>
                    Hi, im Tashinga, a full-stack JavaScript developer.
                  </h1>
                  <p className='max-w-[30rem] sm:text-xl  lg:text-2xl text-primary-100 font-light'>
                    I'm currently looking for my next opportunity to make more
                    kickass software on the web.
                  </p>
                  <div className='flex gap-3 mt-10'>
                    <Link href='/'>
                      <a className='px-6 py-3 bg-primary-100 hover:bg-primary-200 text-primary-500 flex items-center gap-2 text-lg tracking-tight '>
                        My CV
                      </a>
                    </Link>

                    <Link href='/'>
                      <a className='px-6 py-3 bg-primary-500 hover:bg-primary-400 text-white flex items-center gap-2 text-lg tracking-tight '>
                        My Portfolio
                      </a>
                    </Link>
                  </div>
                </div>
                <div className='hidden md:block col-span-2'>
                  <Image
                    src='/images/about-me-image-cluster.png'
                    width={500}
                    height={500}
                    layout='intrinsic'
                    className='object-center object-cover'
                    alt=''
                  />
                </div>
              </article>
              <TechSlider />
            </section>
            <section className='grid gap-8'>
              <h2 className='flex gap-4 text-xl md:text-2xl font-bold items-center'>
                <span className='shrink-0'>Featured Projects</span>
                <hr className='shrink h-1 w-full opacity-30' />
              </h2>
              <div className='grid gap-10 md:gap-14'>
                <article className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3'>
                  Project 1
                </article>
                <article>Project 2</article>
              </div>
            </section>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
